[colors.bright]
black = "#575656"
blue = "#82aaff"
cyan = "#7fdbca"
green = "#22da6e"
magenta = "#c792ea"
red = "#ef5350"
white = "#ffffff"
yellow = "#ffeb95"

[colors.cursor]
cursor = "#33FF33"
text = "#011627"

[colors.normal]
black = "#011627"
blue = "#82aaff"
cyan = "#21c7a8"
green = "#22da6e"
magenta = "#c792ea"
red = "#ef5350"
white = "#ffffff"
yellow = "#c5e478"

[colors.primary]
background = "#1E1E1E"
foreground = "#d6deeb"

[colors.selection]
background = "#ffff33"

[cursor]
style = "block"
unfocused_hollow = true

[font]
size = 9.2

[font.bold]
family = "MonoLisa-Bold"
style = "Bold"

[font.bold_italic]
family = "MonoLisa-Black"
style = "Blod"

[font.italic]
family = "MonoLisa-MediumItalic"
style = "Italic"

[font.normal]
family = "MonoLisa-Regular"
style = "regular"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[scrolling]
history = 3000
multiplier = 3

[shell]
args = ["-l", "-c", "$HOME/pure/coo/open.sh"]
program = "/bin/bash"

[window]
opacity = 1

# Super+数字切换 tmux 窗口
[[keyboard.bindings]]
key = "1"
mods = "Super"
chars = "\u001b1"

[[keyboard.bindings]]
key = "2"
mods = "Super"
chars = "\u001b2"

[[keyboard.bindings]]
key = "3"
mods = "Super"
chars = "\u001b3"

[[keyboard.bindings]]
key = "4"
mods = "Super"
chars = "\u001b4"

[[keyboard.bindings]]
key = "5"
mods = "Super"
chars = "\u001b5"

[[keyboard.bindings]]
key = "6"
mods = "Super"
chars = "\u001b6"

[[keyboard.bindings]]
key = "7"
mods = "Super"
chars = "\u001b7"

[[keyboard.bindings]]
key = "8"
mods = "Super"
chars = "\u001b8"

[[keyboard.bindings]]
key = "9"
mods = "Super"
chars = "\u001b9"


